[package]
name = "hobbs04067/playerindexer"
description = "A 8-bit player integer ID system meant for network optimization. By default, Roblox Player instances require 5 bytes to send over a network. This sytem uses a synced 8bit index system to reduce the packet size."
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://github.com/Hobbs04067/PlayerIndexer"
realm = "shared"

exclude = ["**"]
include = [
    "src",
    "src/*",
    "default.project.json",
    "wally.lock",
    "wally.toml"
]

[dependencies]
